### PR TITLE
Kubi

### PR DESCRIPTION
**Pull request by kubisertoglu**
pls check my code guys

### CODE REVIEW

**Review by HarryFossey — APPROVED** [review]

**Review by HarryFossey — APPROVED** [review]

**Review by DanielWilliams27 — CHANGES_REQUESTED** [review]
Have less space.

**Review by shaythorn97 — APPROVED** [review]
Its amazing!

**Review by HarryFossey — APPROVED** [review]

**Review by kubisertoglu — COMMENTED** [review]
great

**Review by mangahisjohn — APPROVED** [review]
nice!

**Review by DanielWilliams27 — APPROVED** [review]
great

**Pull request merged**
